# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Shawn Wallace
author: Shawn Wallace
email: shawn@wshawn.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website for Shawn Wallace.
domain: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.shawnewallace.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ShawnWallace
github_username:  shawnewallace
linkedin_username: shawnwallace
youtube_username: shawnewallace
show_excerpts: true



# Build settings
# theme: minima
remote_theme: daattali/beautiful-jekyll@5.0.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# CUSTOM
navbar-links:
  About Me: "about"
  Resume/CV: "resume"
  Now: "now"
  Resources:
      - Tags: "tags"
  #   - Beautiful Jekyll: "https://beautifuljekyll.com"
  #   - Learn markdown: "https://www.markdowntutorial.com/"
  # Author's home: "https://deanattali.com"

avatar: "/assets/img/headshot.jpg"
round-avatar: true

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

social-network-links:
  email: "shawn@wshawn.com"
  rss: true 
  facebook: shawn.wallace
  github: shawnewallace
  twitter: ShawnWallace
  youtube: c/shawnewallace
  linkedin: shawnwallace

url-pretty: "shawnewallace.com"
post-search: true

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#FF000A" #???
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#FF000A" #???

site-css:
  - "/assets/css/custom-styles.css"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Output options (more information on Jekyll's site)
timezone: "America/New_York"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"
