# Site settings
title: I'm in o-HI-o
header-img: img/home-bg.jpg
email: shawn@wshawn.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
#url: "http://yourdomain.com"
twitter_username: ShawnWallace
github_username:  shawnewallace
facebook_username:  shawn.wallace
linkedin_username: shawnwallace

markdown: kramdown
highlighter: pygments
permalink: pretty #/blog/:title
paginate: 10
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp","less","node_modules","Gruntfile.js","package.json","README.md"]
future: false